# This is a basic workflow to help you get started with Actions

name: CI


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
       - name: Run markdown lint
        run: |
          npm install remark-cli remark-present-lint-consistent
          npx remark . --use remark-present-lint-consistent --frail
